version: '3.3'
services:
  api:
    container_name: 'api'
    build: './api'
    ports:
      - target: 8080
        published: 8888
        protocol: tcp
        mode: host
    volumes:
      - './api:/go/src/app'
    depends_on:
      - 'mysql'
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql'
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: nutri
    ports:
      - '8383:8383'
