version: '3.3'
services:
  api:
    container_name: 'api'
    build: './api'
    ports:
      - target: 8080
        published: 8888
        protocol: tcp
        mode: host
    volumes:
      - './api:/go/src/app'
    env_file:
      - .env
    depends_on:
      - 'mysql'
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql'
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
volumes:
  db_data:
